site_name: TiTiler.PgSTAC
site_description: Dynamic Mosaics From PgSTAC database.

docs_dir: 'src'
site_dir: 'build'

repo_name: stac-utils/titiler-pgstac
repo_url: https://github.com/stac-utils/titiler-pgstac
edit_uri: blob/main/docs/
site_url: https://stac-utils.github.io/titiler-pgstac/

extra:
  social:
    - icon: "fontawesome/brands/github"
      link: "https://github.com/stac-utils"
  version:
    provider: mike
    default: latest

nav:
  - Home: "index.md"
  - Intro: "intro.md"
  - Endpoints:
    - Searches: "searches_endpoints.md"
    - Collections: "collections_endpoints.md"
    - Items: "items_endpoints.md"
    - TileMatrixSet: "tms_endpoints.md"
  - Tiler Factories: "tiler_factories.md"
  - Advanced usage:
    - Mosaic metadata specification: "advanced/metadata.md"
    - Mosaic list: "advanced/searches_list.md"
    - Custom search model: "advanced/custom_search.md"
    - Custom TileJSON endpoint : "advanced/custom_tilejson.md"
  - Examples:
    - demo: "notebooks/demo.ipynb"
  - API:
    - titiler.pgstac:
      - db: api/titiler/pgstac/db.md
      - dependencies: api/titiler/pgstac/dependencies.md
      - extensions: api/titiler/pgstac/extensions.md
      - factory: api/titiler/pgstac/factory.md
      - model: api/titiler/pgstac/model.md
      - mosaic: api/titiler/pgstac/mosaic.md
      - reader: api/titiler/pgstac/reader.md
      - settings: api/titiler/pgstac/settings.md
      - utils: api/titiler/pgstac/utils.md
  - Migration Guides:
    - v0.8 -> v1.0: 'migrations/v1_migration.md'
  - Development - Contributing: "contributing.md"
  - Release notes: "release-notes.md"
  - Performance Benchmarks: benchmark.html

plugins:
  - search
  - mkdocs-jupyter:
      include_source: True

theme:
  name: material
  favicon: img/favicon.ico
  logo: img/logo.png

extra_css:
  - overrides/stylesheets/extra.css

# https://github.com/kylebarron/cogeo-mosaic/blob/mkdocs/mkdocs.yml#L50-L75
markdown_extensions:
  - admonition
  - attr_list
  - codehilite:
      guess_lang: false
  - def_list
  - footnotes
  - pymdownx.arithmatex
  - pymdownx.betterem
  - pymdownx.caret:
      insert: false
  - pymdownx.details
  - pymdownx.emoji
  - pymdownx.escapeall:
      hardbreak: true
      nbsp: true
  - pymdownx.magiclink:
      hide_protocol: true
      repo_url_shortener: true
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
  - toc:
      permalink: true
