name: Publish docs via GitHub Pages

on:
  push:
    branches:
      - main
    paths:
      # Only rebuild website when docs have changed
      - 'README.md'
      - 'CHANGES.md'
      - 'CONTRIBUTING.md'
      - 'docs/**'
      - 'mkdocs.yml'
      - '.github/workflows/deploy_mkdocs.yml'

jobs:
  build:
    name: Deploy docs
    runs-on: ubuntu-latest
    steps:
      - name: Checkout main
        uses: actions/checkout@v2

      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install -e ".[psycopg-binary]"
          python -m pip install nbconvert==6.5.3 mkdocs mkdocs-material mkdocs-jupyter pygments pdocs mike

      - name: update API docs
        run: |
          pdocs as_markdown \
            --output_dir docs/src/api \
            --exclude_source \
            --overwrite \
            titiler.pgstac.db \
            titiler.pgstac.dependencies \
            titiler.pgstac.extensions \
            titiler.pgstac.factory \
            titiler.pgstac.model \
            titiler.pgstac.mosaic \
            titiler.pgstac.reader \
            titiler.pgstac.settings \
            titiler.pgstac.utils

      - name: Set module version
        id: module
        run: |
          echo version=$(python -c'import titiler.pgstac; print(titiler.pgstac.__version__)') >> $GITHUB_OUTPUT

      - name: Configure Git user
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com

      - name: Fetch gh-pages repository
        run: |
          git fetch origin gh-pages --depth=1

      - name: Deploy documentation
        if: ${{ github.ref_type == 'branch' }}
        run: |
          mike deploy --push --update-aliases latest --config-file docs/mkdocs.yml
          mike set-default --push latest --config-file docs/mkdocs.yml

      - name: Deploy documentation and update alias for latest
        if: startsWith(github.event.ref, 'refs/tags') || github.event_name == 'release'
        run: |
          mike deploy --push --update-aliases ${{ steps.module.outputs.version}} latest --config-file docs/mkdocs.yml
          mike set-default --push latest --config-file docs/mkdocs.yml
