name: Publish docs via GitHub Pages

on:
  push:
    branches:
      - main
    paths:
      # Only rebuild website when docs have changed
      - 'README.md'
      - 'CHANGES.md'
      - 'CONTRIBUTING.md'
      - 'docs/**'
      - 'mkdocs.yml'

jobs:
  build:
    name: Deploy docs
    runs-on: ubuntu-latest
    steps:
      - name: Checkout main
        uses: actions/checkout@v2

      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install .
          python -m pip install nbconvert==6.5.3 mkdocs mkdocs-material mkdocs-jupyter pygments pdocs

      - name: update API docs
        run: |
          pdocs as_markdown \
            --output_dir docs/src/api \
            --exclude_source \
            --overwrite \
            titiler.pgstac.db \
            titiler.pgstac.dependencies \
            titiler.pgstac.extensions \
            titiler.pgstac.factory \
            titiler.pgstac.model \
            titiler.pgstac.mosaic \
            titiler.pgstac.reader \
            titiler.pgstac.settings \
            titiler.pgstac.utils

      - name: Deploy docs
        run: mkdocs gh-deploy -f docs/mkdocs.yml --force
